### PR TITLE
fix: exit with code 1 on error

### PR DESCRIPTION
**Pull request by busser**
## Refactor

- Remove usage of `panic`
- Inject dependencies into `transform` function

## Tests

- Add unit tests for `transform` function

### CODE REVIEW

**Comment by JulienBreux** [comment]
I've a doubt about `panic`.

Because, in your case, this `clamp > xxx.test` produce `cat xxx.test == clamp: %s\n`

It's not predictable.

And `os.Exit(1)` is used with `$?` in bash.

**Comment by busser** [comment]
I agree that when an error occurs `clamp` should have an exit code of `1`. I've added that back.

I'm not sure I understand your example though. When an error occurs, the error is printed to standard error and nothing is printed to standard output. For example, this is the behaviour I have:

```
$ go build
$ echo 'Hello {{ .USER }}!' | ./clamp > xxx.test
$ cat xxx.test
Hello arthur!
$ echo 'Hello {{ foo .USER }}!' | ./clamp > xxx.test
clamp: could not render: template: default:1: function "foo" not defined
$ cat xxx.test
$
```

Is this not the behaviour we expect from `clamp`?

**Comment by busser** [comment]
Since #6 was merged, this PR adds only the following fix:

- Set exit code to 1 when an error occurs

**Comment by busser** [comment]
@JulienBreux I think this PR is required to fix a breaking change introduced when merging #6.

**Review by JulienBreux — DISMISSED** [review]

**Comment by JulienBreux** [comment]
Please rebase your branch 🤗
Thanks

**Comment by busser** [comment]
@JulienBreux Branch rebased 👍

**Review by JulienBreux — APPROVED** [review]
LGTM

**Pull request merged**
